### ISSUE TITLE
Modal overlay doesn't change the whole background's opacity

### ISSUE THREAD

**Issue by thellimist** [rackt/react-modal#113]
As you can see there is a line(blue line) where the opacity is not set by the modal. The css of the dragbar is 
```
#side-dragbar {
    position: absolute;
    background-color: #377CE4;
    min-height: 100%;
    width: 3px;
    cursor: col-resize;
    z-index: 1;
}
```
Do you have any ideas what can be the problem?  

![](http://i.imgur.com/YyfGnV3.png)

**Comment by liwp** [comment]
@thellimist I think the cause is the `z-index: 1;` line in your CSS: the overlay has a `z-index` of `0`, so your CSS lifts the dragbar above the overlay.

You can fix this by specifying a higher `z-index` for the overlay either in CSS:

```css
.ReactModal__Overlay {
  ...
  z-index: 1000; /* Must be greater than #side-dragbar:z-index */
}
```

...or in the inline styles:

```
<Modal ... style={{overlay: {zIndex: 1000}}}>
  ...
</Modal>
```
